main = "./src/index.ts"
name = "bookmark-service"
compatibility_date = "2022-07-26"
kv_namespaces = [{binding = "BOOKMARK", id = "abaeaa86bb394b70b94099de493c40aa", preview_id = "ad8b00d2c69549f296a8b57cb3ae65d2"}]