name = "hub-bookmark"
main = "src/index.ts"
compatibility_date = "2022-12-20"

kv_namespaces = [{binding = "BOOKMARK", id = "abaeaa86bb394b70b94099de493c40aa", preview_id = "ad8b00d2c69549f296a8b57cb3ae65d2"}]
[env.dev]
kv_namespaces = [{binding = "BOOKMARK", id = "abaeaa86bb394b70b94099de493c40aa", preview_id = "ad8b00d2c69549f296a8b57cb3ae65d2"}]
[env.dev.vars]
PRESHARED_AUTH_HEADER_KEY="x-custom-obscured-header"
PRESHARED_AUTH_HEADER_VALUE="a-very-secure-key"